export const STATE_KEY = 'populations';

export const GENERATE_POPULATION = `${STATE_KEY}/GENERATE_POPULATION`;
export const GET_POPULATION = `${STATE_KEY}/GET_POPULATION`;
export const STORE_POPULATION_ID = `${STATE_KEY}/STORE_POPULATION_ID`;
export const SET_CURRENT_POPULATION = `${STATE_KEY}/SET_CURRENT_POPULATION`;